KS-7-5
Areiwei/KotlinSprint pull request #36
Opened 2024-03-17 13:02 UTC by Areiwei

2024-03-18 06:07 UTC, ievetrovdev requested changes

2024-03-18 06:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    var listOfSymbols = (rangePassWords.toList() + rangePassNumbers.toList() + rangePassCapWords.toList())
по умолчанию все переменные делаем val и приведение к листу toList здесь можно удалить

2024-03-18 06:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    val generatedPassword = shuffledSymbols.substring(0, inputRange)
в таком варианте мы не можем гарантировать, что в пароле будут присутствовать все 3 вида символов
`должны присутствовать все три вида символов`

2024-03-18 19:31 UTC, Areiwei commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +
Пришлось узнать много нового, чтобы это реализовать...

2024-03-19 17:26 UTC, ievetrovdev approved these changes

2024-03-19 18:26 UTC, merged