KS-9-3
Areiwei/KotlinSprint pull request #44
Opened 2024-03-19 19:41 UTC by Areiwei

2024-03-20 07:09 UTC, ievetrovdev requested changes

2024-03-20 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task3.kt
> +        "На $countPortion порций вам понадобится: яиц ${countPortion * omeletteIngredients[0]} шт.," +
Используй функцию map для этих целей) и каждый элемент интерации будем перемножать

2024-03-20 17:23 UTC, Areiwei commented on src/main/kotlin/lesson_9/lesson9_task3.kt
> -}
Как же изящен стал код!

2024-03-21 07:50 UTC, ievetrovdev approved these changes

2024-03-21 08:46 UTC, merged